$icon16 = "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAYklEQVR42mNkQAO/gJiJgYEhmoGBgQ0qB5NhwGcmBgaGeCgNJseAz0wIDEwMscgGoJvBhN+Az0wIDCRDkD2A7gJ0A4g1gO4CdAOINYDuAnQDiDWA7gJ0A9DDAL8hWNgwHACXNyoR1c4q4wAAAABJRU5ErkJggg=="

$icon48 = "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAABJElEQVR42u2ZsQ3CMBBFX8UCrMAIDMAMjMASdMAMgMQAqEiJEUiJEQiJEShYoqBgiSVEsuMcx0dI/vTpV5/tKy/3dD5JkiRJkiT/NFsAd+AWuAGugRvgGbgGauAYuAFugZvtA9yAW2ATmIEJmAhGgRFgFBgBRoERYBQYAUaBUWAUGIGkFpgAk8AkMAmMAiPAKDACjAKjwAgwCiwDpsAkMAmMAktXwE1/gI8X7vP6V/qL/N0XQGkP8B7BvK8/W1v7+gP0l7kFvgEewTugB+gB10B/mAewATyCR8AjsAf0AD3gGugP8wB2gEfwCPgH9AA94BroD/MABsAj4BF4BPaAHqAHXAP9YV7+K+ANcAWm/Vf8T6C9bTvwDPixWcAYsAlswEqSJEkSqfQGiX94Jk74CgIAAAAASUVORK5CYII="

$icon128 = "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAACPUlEQVR42u3dsQ3CQBAEwbsCoiIqoiIiMgoiogKiIioioiIqoiAiooAVwLIDlh3neQ9XFjrf8WqTJEeSJEeSJEmyvOwAnIEbcAVuwAW4AVfgBlyBG3ABbsANuAEX4A6cgRtwA27ADbgAN+AGXIAbsAWu/TtwA27ADbgAd+AC3IAbcANuwAW4ATfgBtyAG3ADbsANuAEX4AZcgRtwtTPAE3gCT+AJPIEn8ASewBN4Ak/gCTyBJ/AEnsATeAJP4Ak8gSfwBJ7AE3gCT+AJPEFtgDvwCN4BvcAe0APsAb3AHtAL7AG9wB7QC+wBvcAe0AvsAb3AHtAL7AG9wB7QC+wBvcAe0AvsAdUB7sAjeAf0AntAD7AH9AJ7QC+wBvcAe0AvsAb0AntAD7AH9AJ7QC+wBvcAe0AvsAf0AntAdYA78AjeAb3ADtAD7QG9wB7QC+wBvcAe0AvsAb3AHtAL7AG9wB7QC+wBvcAe0AvsAb3AHlAd4A48gndAD7AH9AJ7QC+wBvcAe0AvsAb0AntAD7AH9AJ7QC+wBvcAe0AvsAf0AntAD7QHVAe4A4/gHdAD7AE9wB7QC+wBvcAe0AvsAb3AHtAL7AG9wB7QC+wBvcAe0AvsAb3AHtAJ8ASewBN4Ak/gCTyBJ/AEnsATeAJP4Ak8gSfwBJ7AE3gCT+AJPIEn8ASewBN4Ak/gCTyBP+AD8AjegRPgN0mSJEmy4u4M8ATewA24ATfgBlyBG3ABbsANuAEX4AbcgBtwA27ADbi5ewGSwE5t1GwqVAAAAABJRU5ErkJggg=="

$destDir = Join-Path $PSScriptRoot "doomscroll-blocker/icons"

if (-not (Test-Path $destDir)) {
    New-Item -ItemType Directory -Force -Path $destDir | Out-Null
}

[System.IO.File]::WriteAllBytes((Join-Path $destDir "icon-16.png"), [System.Convert]::FromBase64String($icon16))
[System.IO.File]::WriteAllBytes((Join-Path $destDir "icon-48.png"), [System.Convert]::FromBase64String($icon48))
[System.IO.File]::WriteAllBytes((Join-Path $destDir "icon-128.png"), [System.Convert]::FromBase64String($icon128))

Write-Host "Icons generated successfully in $destDir"
